name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  ci:
    name: Run Tests
    uses: ./.github/workflows/tests.yml

  publish:
    name: Publish to Packagist
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Packagist
        env:
          PACKAGIST_API_TOKEN: ${{ secrets.PACKAGIST_API_TOKEN }}
          PACKAGIST_USER_NAME: lucianotonet
        run: |
          composer_name=$(grep -oP '"name":\s*"\K[^"]+' composer.json)
          echo "Notifying Packagist about new version for $composer_name..."
          response_code=$(curl -s -w "%{http_code}" -X POST \
            -H "Content-type: application/json" \
            "https://packagist.org/api/update-package?username=${PACKAGIST_USER_NAME}&apiToken=${PACKAGIST_API_TOKEN}" \
            -d "{\"repository\":{\"url\":\"https://github.com/${GITHUB_REPOSITORY}\"}}" \
            -o response.txt)
          cat response.txt
          if [ "$response_code" -ne 202 ] && [ "$response_code" -ne 200 ]; then
            echo "Error updating Packagist: HTTP $response_code"
            exit 1
          fi
          echo "Packagist updated successfully."
